# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rbbt-text}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Miguel Vazquez"]
  s.date = %q{2010-12-14}
  s.description = %q{Text mining tools: named entity recognition and normalization, document classification, bag-of-words, dictionaries, etc}
  s.email = %q{miguel.vazquez@fdi.ucm.es}
  s.files = [
    "lib/rbbt/bow/bow.rb",
    "lib/rbbt/bow/dictionary.rb",
    "lib/rbbt/bow/misc.rb",
    "lib/rbbt/ner/abner.rb",
    "lib/rbbt/ner/banner.rb",
    "lib/rbbt/ner/named_entity.rb",
    "lib/rbbt/ner/oscar3.rb",
    "lib/rbbt/ner/regexpNER.rb",
    "share/install/software/ABNER",
    "share/install/software/BANNER",
    "share/install/software/OSCAR3",
    "share/stopwords"
  ]
  s.homepage = %q{http://github.com/mikisvaz/rbbt-util}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Text mining tools for the Ruby Bioinformatics Toolkit (rbbt)}
  s.test_files = [
    "test/rbbt/bow/test_bow.rb",
    "test/rbbt/bow/test_dictionary.rb",
    "test/rbbt/bow/test_misc.rb",
    "test/rbbt/ner/test_abner.rb",
    "test/rbbt/ner/test_banner.rb",
    "test/rbbt/ner/test_named_entity.rb",
    "test/rbbt/ner/test_oscar3.rb",
    "test/rbbt/ner/test_regexpNER.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rbbt-util>, [">= 0"])
      s.add_runtime_dependency(%q<stemmer>, [">= 0"])
    else
      s.add_dependency(%q<rbbt-util>, [">= 0"])
      s.add_dependency(%q<stemmer>, [">= 0"])
    end
  else
    s.add_dependency(%q<rbbt-util>, [">= 0"])
    s.add_dependency(%q<stemmer>, [">= 0"])
  end
end

