#!/bin/bash

INSTALL_HELPER_FILE="$1"
RBBT_SOFTWARE_DIR="$2"
source "$INSTALL_HELPER_FILE"

name='Geniass'
url="http://www.nactem.ac.uk/y-matsu/geniass/geniass-1.00.tar.gz"


get_pkg "$name" "$url"
uncompress_pkg "$name"

cd "$(echo $OPT_BUILD_DIR/`ls $OPT_BUILD_DIR |head -n 1`)" 

pwd > /tmp/pwd
ls > /tmp/ls

cat >> Makefile <<'EOF'
libgeniass.so: maxent.o  blmvm.o
	$(CXX) $(CFLAGS) -o $@ -shared $^
EOF

cat Makefile| sed 's/\(CFLAGS\s*=\)/\1 -fPIC/' > /tmp/clean.Makefile
mv /tmp/clean.Makefile Makefile

make geniass
make libgeniass.so

mkdir lib
mv libgeniass.so lib

build "$name" "$extra"

cd "$OPT_BUILD_DIR/$name"

mkdir ruby
cat > ruby/extconf.rb <<'EOF'
require 'mkmf-rice'
dir_config('geniass')
have_library('geniass')
create_makefile('Geniass')
EOF

cat > ruby/Geniass.cpp <<'EOF'
#include "rice/Class.hpp"
#include "rice/String.hpp"

#include <iostream>
#include <iomanip>
#include <string>
#include <list>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include "../maxent.h"

using namespace Rice;
using namespace std;

ME_Model model;
bool geniass_loaded = false;

void load_geniass(){
    printf("loading model");
    string modelFile = "model1-1.0";
    model.load_from_file(modelFile.c_str());
    geniass_loaded = true;
    printf("..done\n");
}

bool geniass_is_loaded(){ return(geniass_loaded); };

void split(string& str, vector<string>& tokens)
{
    istringstream in(str);
    char c;

    while (in){
        string token;
        token = "";
        while (in.get(c) && (c != '\t')) token.push_back(c);
        tokens.push_back(token);
    }
}

string label(string line){
    vector<string> tokens;
    split(line, tokens);
    ME_Sample s;

    for(vector<string>::const_iterator token = tokens.begin() + 1;
        token != tokens.end(); ++token){
        s.add_feature(*token);
    }
    (void) model.classify(s);
    return(s.label);
}

extern "C"
void Init_Geniass()
{
  Class rb_cGeniass =
    define_class("Geniass")
    .define_method("load_geniass", &load_geniass)
    .define_method("label", &label)
    .define_method("geniass_is_loaded", &geniass_is_loaded);
}

EOF

cd ruby
ruby extconf.rb --with-geniass-dir="$OPT_DIR/$name"  
make



