#!/bin/bash

name='OpenNLP'
url="http://apache.rediris.es/opennlp/opennlp-1.9.1/apache-opennlp-1.9.1-bin.tar.gz"

get_src "$name" "$url"
move_opt "$name" 


ln -sf  "$OPT_DIR/$name/lib/"*.jar  "$OPT_JAR_DIR/"

clean_build
